version: 1.0

jobs:
  myjob:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run:
          name: Download/Extract-ThunderScan-API-CLI-Client
          command: |
            wget https://download.defensecode.com/latest/archives-tar/thunderscan-cli.tar.gz -O thunderscan-cli.tar.gz
            tar xvzf thunderscan-cli.tar.gz
      - run:
          name: Run ThunderScan CLI Client
          command: |
            ./thunderscan-cli

workflows:
  version: 2
  build_and_test:
    jobs:
      - myjob